### ISSUE TITLE
Withdrawal issue: funds did not arrive.

### ISSUE THREAD

**Issue by SergProk** [iotapoker/issues#10]
I played iota poker today for the first time. 2 deposits (90 and 50 )were almost instant. 
I tried to withdraw 170. The amount was deducted form my account but did not arrive in my wallet. 
My iotapoker username is LLlapuk. 
Happened around 2 to 1 hours ago.

**Comment by iotapoker** [comment]
@SergProk  Hi, the withdrawals can sometimes take up to 24h if node connection failed as stated in the message you get when withdrawing. Please don't open the ticket if 24h didn't pass.
