### ISSUE TITLE
transfer did not go through

### ISSUE THREAD

**Issue by goodlocks** [iotapoker/issues#11]
tokens i sent to your site were not posted to my account. i sent about $53 here 
iota1qq80wtfdl9xgzsqc45gv69yctfwhkqndlhm9sslufs6yr2zulynsk80acdd

**Comment by iotapoker** [comment]
@goodlocks The tokens are available on the address as visible here: https://explorer.iota.org/mainnet/addr/iota1qq80wtfdl9xgzsqc45gv69yctfwhkqndlhm9sslufs6yr2zulynsk80acdd
You have to press the Refresh button on the deposit screen.

Please read the guide carefully before opening a ticket here.
