### ISSUE TITLE
Rake

### ISSUE THREAD

**Issue by Deweypoka** [iotapoker/issues#13]
No rake when there is no pot (flop...)
For example: If I 3bet and everybody folds then there should not be rake!
For example: If I open and everybody folds then there should not be rake!

More transparency about the rake would be cool. A replay function of the previous hands (where you can also see the won/lost pot and the paid rake would be cool) would be great

**Comment by iotapoker** [comment]
Thanks for the suggestion. This will be considered later - the focus is now on new features and UX.
Replay function is already on the roadmap.
