### ISSUE TITLE
I want to report 2 players for play in the team

### ISSUE THREAD

**Issue by pedjamaric** [iotapoker/issues#14]
On iotapoker.app site players with usernames DeweyMalcolm and Quaksi play together they tell each other what cards they have, Pay attention. It is not fair play, they would be instantly banned from any other poker site for it.

**Comment by Deweypoka** [comment]
Lol...You are talking bullshit.

**Comment by Deweypoka** [comment]
There are like 10 players who are playing daily. If two players are playing more then 3 times at the same time against you than they are cheating?? LOL

**Comment by iotapoker** [comment]
Cheating in any form is unacceptable in this game, these things are hard to stop but is monitored continuously. If any suspicious behaviour is noticed players will be blocked from joining tables.
