### ISSUE TITLE
Cannot withdraw

### ISSUE THREAD

**Issue by y405** [iotapoker/issues#15]

**Comment by iotapoker** [comment]
Please provide more details or this issue will be closed.

**Comment by y405** [comment]
<img width="1078" alt="Capture d’écran 2022-04-02 à 18 22 36" src="https://user-images.githubusercontent.com/2266373/161380894-f437f8cd-6b62-4dc2-9d6a-379d18a3968c.png">

**Comment by y405** [comment]
Just try to withdraw, and have this error

**Comment by iotapoker** [comment]
What is your player name?
We didn't receive any withdrawal requests today, can you try it again and see what happens?

**Comment by y405** [comment]
Leay, I try again now and same error. Tell me I cannot right now, have to try later

**Comment by iotapoker** [comment]
You have to leave the table seat before you can withdraw tokens, the message will be fixed thanks for reporting this.
