### ISSUE TITLE
HU sb and bb

### ISSUE THREAD

**Issue by Deweypoka** [iotapoker/issues#4]
In heads up the player in the button has the sb and acts first and the opponent has the bb.
You have to change this.
Greatings

**Comment by iotapoker** [comment]
Checked now, in 1 on 1, the button player has BB and the opponent has SB. The opponent is first on move.
It looks like it works as expected, or did I miss something?

**Comment by Deweypoka** [comment]
in 1 on 1 the button player has the sb and the other the bb

**Comment by iotapoker** [comment]
@Deweypoka This is now fixed. In heads up, the button player bets small blind, and the other player bets big blind.
