### ISSUE TITLE
withdrawal bug

### ISSUE THREAD

**Issue by Cayyyysad** [iotapoker/issues#9]
another withrawal bug - 250 mi

iota1qzwvyjk30wajckvsj6z47nllmf57cwyp5c2s8cx7n3zsn5jffm0d7k25thc

asiatkofil@seznam.cz

**Comment by iotapoker** [comment]
@Cayyyysad Thanks for opening the ticket. Sometimes tokens are not sent automatically due to node connection. The tokens are resent to you automatically within 24 hours. If that doesn't happen then open the ticket.

The error message you receive will be updated to make it clear.
